export enum SCREEN_STACK_ENUM {
  NFT = 'NFT',
  HOME = 'HOME',
  SEARCH = 'SEARCH',
  DETAIL = 'DETAIL',
  TWITTER = 'TWITTER',
  BUTTOMTABS = 'BUTTOMTABS',
  LEADERBOARD = 'LEADERBOARD',
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  NFT_TRENDING_LIST = 'NFT_TRENDING_LIST',
  FAVORITE_NFT_LIST = 'FAVORITE_NFT_LIST',
  MARKETPLACE_NFT_LISTING = 'MARKETPLACE_NFT_LISTING',
}
